### ISSUE TITLE
face doesn't sync/move

### ISSUE THREAD

**Issue by Mremenar** [alievk/avatarify-desktop#28]
Hi!  Very excited that you have made a windows compatible version of Avatarify!  Thank you for that!  I have the software installed, and have input faces I would like to use.  The problem is that  when I calibrate the selected face to my face no actual face movement of the mouth occurs.  The eyes bug out and twitterpate, but no actual movement to sync up with mouth movement for speech.  The whole face twitches and has mild distortion which looks very  'unrealistic.'  This problem occurs also with all the "stock" faces that come with the software install.
I have a 1080TI cuda card.

**Comment by JohanAR** [comment]
Did you select the correct webcam and calibrated it to your face?

If you have calibrated already, is your face properly illuminated and centered in the web cam view? The problem you describe sounds like what happens if it's too dark in the room, or if the camera is either too close or too far from your face.

**Comment by Mremenar** [comment]
You are correct. By changing distance between my face and the camera,  I was able to overcome this problem.  Thank you.
